# Generated by Django 2.2.10 on 2021-09-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('date_a', models.DateField(verbose_name='Дата начала')),
                ('date_b', models.DateField(verbose_name='Дата завершения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-date_a'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Вопрос')),
                ('type', models.CharField(choices=[('FC', 'Свободная формулировка ответа'), ('OO', 'Выбор одного варианта ответа'), ('MO', 'Выбор нескольких вариантов ответа')], max_length=2, verbose_name='Тип вопроса')),
                ('option1', models.CharField(blank=True, max_length=64, null=True, verbose_name='Вариант ответа Б')),
                ('option0', models.CharField(blank=True, max_length=64, null=True, verbose_name='Вариант ответа А')),
                ('option2', models.CharField(blank=True, max_length=64, null=True, verbose_name='Вариант ответа В')),
                ('option3', models.CharField(blank=True, max_length=64, null=True, verbose_name='Вариант ответа Г')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-poll'],
            },
        ),
    ]
