# Generated by Django 2.2.10 on 2021-09-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210915_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option0',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Вариант ответа А'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Вариант ответа Б'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Вариант ответа В'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Вариант ответа Г'),
        ),
    ]
