# Generated by Django 2.2.10 on 2021-10-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='poll',
        ),
    ]
