# Generated by Django 2.2.10 on 2021-11-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211101_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='respondent',
            field=models.CharField(max_length=64, verbose_name='Пользователь'),
        ),
    ]
